# Generated by Django 4.2.11 on 2025-11-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Categories", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("expiry_date", models.DateField()),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, help_text="Optional: For data analysis", null=True
                    ),
                ),
                (
                    "store_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["expiry_date"],},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "barcode",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Scraped image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an attractive image to override the scraped URL.",
                        null=True,
                        upload_to="product_images/",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nutriscore_grade",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="Inventory.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supermarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description of the supermarket.",
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="supermarket_logos/"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Street Address, City, Postal Code",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        help_text="e.g., {'Monday': '09:00-20:00', 'Tuesday': '09:00-20:00'}",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_supermarkets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MANAGER", "Manager"),
                            ("STAFF", "Staff"),
                        ],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                ("can_edit_prices", models.BooleanField(default=False)),
                ("can_delete_items", models.BooleanField(default=False)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="racks",
                        to="Inventory.supermarket",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The default category for this product at this supermarket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventory.category",
                    ),
                ),
                (
                    "default_rack",
                    models.ForeignKey(
                        blank=True,
                        help_text="The default rack for this product at this supermarket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventory.rack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_listings",
                        to="Inventory.product",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="Inventory.supermarket",
                    ),
                ),
            ],
            options={"ordering": ["product__name"],},
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="Inventory.supplier"
            ),
        ),
    ]
