# Generated by Django 4.2.11 on 2025-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supermarket",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short description of the supermarket.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="supermarket_logos/"
            ),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                help_text="e.g., {'Monday': '09:00-20:00', 'Tuesday': '09:00-20:00'}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="supermarket",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
