# Generated by Django 4.2.11 on 2025-10-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="applied_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="The pricing rule that was last applied.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.pricingrule",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Overrides product's main category if set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_instances",
                to="Inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="pricing.promotion",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="Inventory.rack",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="supermarket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="Inventory.supermarket",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffprofile", unique_together={("user", "supermarket")},
        ),
        migrations.AlterUniqueTogether(
            name="rack", unique_together={("supermarket", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="productprice", unique_together={("supermarket", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={
                ("supermarket", "product", "expiry_date", "rack", "store_price")
            },
        ),
    ]
