# Generated by Django 5.2.6 on 2025-10-31 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='applied_rule',
            field=models.ForeignKey(blank=True, help_text='The pricing rule that was last applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricingrule'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Overrides product's main category if set.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pricing.promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Inventory.category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_instances', to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='The default category for this product at this supermarket.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_listings', to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='default_rack',
            field=models.ForeignKey(blank=True, help_text='The default rack for this product at this supermarket.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.rack'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Inventory.rack'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_supermarkets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='Inventory.supermarket'),
        ),
        migrations.AddField(
            model_name='rack',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='Inventory.supermarket'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='Inventory.supermarket'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Inventory.supermarket'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='Inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='staffprofile',
            unique_together={('user', 'supermarket')},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('supermarket', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('supermarket', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('supermarket', 'product', 'expiry_date', 'rack', 'store_price')},
        ),
    ]
