# Generated by Django 4.2.11 on 2025-09-24 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Inventory", "0002_supermarket_description_supermarket_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="applied_rule",
            field=models.CharField(
                blank=True,
                help_text="The name of the pricing rule that was last applied.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The price paid to the supplier for this item.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="suggested_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price suggested by the pricing strategy.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="store_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The current price the item is sold at in your store.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supermarket",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_supermarkets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage Off"),
                            ("FIXED_AMOUNT", "Fixed Amount Off"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="Inventory.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="Inventory.product"
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="Inventory.supermarket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("MATCH_LOWEST", "Match Lowest Competitor"),
                            ("BEAT_LOWEST", "Beat Lowest Competitor by %"),
                            ("PROFIT_MARGIN", "Maintain Profit Margin %"),
                            ("EXPIRY_DISCOUNT", "Discount by % based on Expiry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage value (e.g., 5 for 5%, 50 for 50%)",
                        max_digits=5,
                    ),
                ),
                (
                    "days_until_expiry",
                    models.IntegerField(
                        blank=True,
                        help_text="Only for Expiry Discount rule type",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower number means higher priority."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.category",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.supplier",
                    ),
                ),
            ],
            options={"ordering": ["priority"],},
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="Inventory.promotion",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="Inventory.supplier"
            ),
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MANAGER", "Manager"),
                            ("STAFF", "Staff"),
                        ],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                ("can_edit_prices", models.BooleanField(default=False)),
                ("can_delete_items", models.BooleanField(default=False)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "supermarket")},},
        ),
    ]
