# Generated by Django 4.2.11 on 2025-12-18 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WastageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_wasted", models.PositiveIntegerField(default=1)),
                (
                    "expiry_date",
                    models.DateField(help_text="Expiry date of the wasted item"),
                ),
                ("date_removed", models.DateTimeField(auto_now_add=True)),
                (
                    "original_store_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-fetched from InventoryItem when saved.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wastage_logs",
                        to="Inventory.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wastage_logs",
                        to="Inventory.product",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastage_logs",
                        to="Inventory.supermarket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wastage Record",
                "verbose_name_plural": "Wastage Records",
                "ordering": ["-date_removed"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage Off"),
                            ("FIXED_AMOUNT", "Fixed Amount Off"),
                            ("BOGO", "Buy X Get Y Free"),
                            ("MULTIPACK", "Bundle Price (X for Y)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Used for percentage or fixed amount discounts",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("buy_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("free_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("pack_qty", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pack_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="Inventory.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="Inventory.product"
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="Inventory.supermarket",
                    ),
                ),
            ],
            options={"ordering": ["-start_date"],},
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("MATCH_LOWEST", "Match Lowest Competitor"),
                            ("BEAT_LOWEST", "Beat Lowest Competitor by %"),
                            ("PROFIT_MARGIN", "Maintain Profit Margin %"),
                            ("EXPIRY_DISCOUNT", "Discount by % based on Expiry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage value (e.g., 5 for 5%, 50 for 50%)",
                        max_digits=5,
                    ),
                ),
                (
                    "days_until_expiry",
                    models.IntegerField(
                        blank=True,
                        help_text="Only for Expiry Discount rule type",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower number means higher priority."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to disable the promotion without deleting it.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.category",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.supplier",
                    ),
                ),
            ],
            options={"ordering": ["priority"],},
        ),
        migrations.CreateModel(
            name="DiscountedSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_sold", models.PositiveIntegerField(default=1)),
                ("date_sold", models.DateTimeField(auto_now_add=True)),
                ("expiry_date_at_sale", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_logs",
                        to="Inventory.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_logs",
                        to="Inventory.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Promotion applied, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pricing.promotion",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_logs",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "triggering_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Pricing Rule applied, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pricing.pricingrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competitor_name", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_prices",
                        to="Inventory.product",
                    ),
                ),
            ],
            options={"ordering": ["-scraped_at"],},
        ),
    ]
