# Generated by Django 5.2.6 on 2025-11-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_productprice_price'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastagerecord',
            name='original_store_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price of the item when it was wasted.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wastagerecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to='Inventory.category'),
        ),
        migrations.AlterField(
            model_name='wastagerecord',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to='Inventory.product'),
        ),
        migrations.AlterField(
            model_name='wastagerecord',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_logs', to='Inventory.supermarket'),
        ),
    ]
