# Generated by Django 5.2.6 on 2025-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_wastagerecord_original_store_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastagerecord',
            options={'ordering': ['-date_removed'], 'verbose_name': 'Wastage Record', 'verbose_name_plural': 'Wastage Records'},
        ),
        migrations.AddField(
            model_name='wastagerecord',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wastagerecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastagerecord',
            name='expiry_date',
            field=models.DateField(help_text='Expiry date of the wasted item'),
        ),
        migrations.AlterField(
            model_name='wastagerecord',
            name='original_store_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-fetched from InventoryItem when saved.', max_digits=10, null=True),
        ),
    ]
