# Generated by Django 5.2.6 on 2025-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_wastagerecord_options_wastagerecord_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='promotion',
            name='buy_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='free_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pack_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FIXED_AMOUNT', 'Fixed Amount Off'), ('BOGO', 'Buy X Get Y Free'), ('MULTIPACK', 'Bundle Price (X for Y)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used for percentage or fixed amount discounts', max_digits=10, null=True),
        ),
    ]
