# Generated by Django 4.2.11 on 2025-12-18 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional internal reference / note for this order.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_batches",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_batches",
                        to="Inventory.supplier",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="ProductPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_barcode",
                    models.CharField(
                        help_text="Consumer Unit (CU) barcode — usually same as Product.barcode",
                        max_length=50,
                    ),
                ),
                (
                    "carton_barcode",
                    models.CharField(
                        help_text="Distribution Unit (DU) barcode — GTIN-14 / Code128 / internal",
                        max_length=50,
                    ),
                ),
                (
                    "units_per_carton",
                    models.PositiveIntegerField(
                        help_text="How many units in one carton (DU)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_options",
                        to="Inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional default supplier for this pack size.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Packaging",
                "verbose_name_plural": "Product Packaging",
                "unique_together": {("product", "unit_barcode", "carton_barcode")},
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_barcode",
                    models.CharField(
                        help_text="Consumer unit barcode (EAN-13).", max_length=50
                    ),
                ),
                (
                    "cartons",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of cartons ordered."
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="order.orderbatch",
                    ),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_lines",
                        to="order.productpackaging",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_lines",
                        to="Inventory.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("batch", "product", "unit_barcode", "packaging")},
            },
        ),
    ]
