# Generated by Django 4.2.11 on 2025-11-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_barcode",
                    models.CharField(
                        help_text="Consumer Unit (CU) barcode — EAN-13", max_length=50
                    ),
                ),
                (
                    "carton_barcode",
                    models.CharField(
                        blank=True,
                        help_text="Distribution Unit (DU) barcode — GTIN-14 / Code128 / internal",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "units_per_carton",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many units in one carton (DU).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_options",
                        to="Inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventory.supplier",
                    ),
                ),
            ],
            options={"unique_together": {("unit_barcode", "carton_barcode")},},
        ),
    ]
