# Generated by Django 4.2.11 on 2025-11-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_initial"),
        ("order", "0002_orderbatch_orderline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderbatch", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(name="orderline", options={},),
        migrations.AlterModelOptions(
            name="productpackaging",
            options={
                "verbose_name": "Product Packaging",
                "verbose_name_plural": "Product Packaging",
            },
        ),
        migrations.AddField(
            model_name="orderbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orderbatch",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Optional internal reference / note for this order.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="carton_barcode",
            field=models.CharField(
                blank=True,
                help_text="Carton barcode if mapped.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="cartons",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of cartons ordered."
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="Inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_barcode",
            field=models.CharField(
                help_text="Consumer unit barcode (EAN-13).", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="units_per_carton",
            field=models.PositiveIntegerField(
                blank=True, help_text="How many units in one carton.", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderline", unique_together={("batch", "product", "unit_barcode")},
        ),
        migrations.RemoveField(model_name="orderline", name="created_at",),
        migrations.RemoveField(model_name="orderline", name="notes",),
    ]
