# Generated by Django 4.2.11 on 2024-04-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seosettings", old_name="page_name", new_name="title",
        ),
    ]
