# Generated by Django 4.2.11 on 2024-05-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_page_name_seosettings_title"),
    ]

    operations = [
        migrations.DeleteModel(name="SEOSettings",),
    ]
