# Generated by Django 4.2.11 on 2025-12-18 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("label_width_mm", models.FloatField()),
                ("label_height_mm", models.FloatField()),
                ("cols", models.PositiveIntegerField()),
                ("rows", models.PositiveIntegerField()),
                ("margin_top_mm", models.FloatField(default=5)),
                ("margin_left_mm", models.FloatField(default=5)),
                ("gap_vertical_mm", models.FloatField(default=2)),
                ("gap_horizontal_mm", models.FloatField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name="TicketTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("text_color", models.CharField(default="#000000", max_length=20)),
                ("accent_color", models.CharField(default="#FF0000", max_length=20)),
                ("width_mm", models.PositiveIntegerField(default=80)),
                ("height_mm", models.PositiveIntegerField(default=50)),
                ("match_product_color", models.BooleanField(default=False)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.supermarket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final price to display on ticket",
                        max_digits=10,
                    ),
                ),
                (
                    "price_per_liter",
                    models.CharField(
                        blank=True,
                        help_text="€/L or €/kg text snapshot",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_brand",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "unit_barcode",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "carton_barcode",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "units_per_carton",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "include_carton_barcode",
                    models.BooleanField(
                        default=False,
                        help_text="If true, carton barcode will be printed",
                    ),
                ),
                (
                    "promo_type",
                    models.CharField(
                        blank=True,
                        help_text="PERCENTAGE / FIXED / BOGO / MULTIPACK / None",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "promo_display",
                    models.CharField(
                        blank=True,
                        help_text="Text shown on ticket (e.g. BUY 2 GET 1)",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "promo_original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price before promo",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Effective promo price snapshot",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = waiting to print", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticketlabel",
                        to="Inventory.product",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_labels",
                        to="Inventory.supermarket",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Tickettheme.tickettheme",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
