# Generated by Django 4.2.11 on 2025-12-18 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "search_url_template",
                    models.CharField(
                        help_text="e.g., https://www.carrefour.fr/s?q={barcode}",
                        max_length=500,
                    ),
                ),
                (
                    "price_selector",
                    models.CharField(
                        help_text="CSS selector for the price tag", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="competitor_logos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompetitorPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scraped_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("product_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitor.competitor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_snapshots",
                        to="Inventory.product",
                    ),
                ),
            ],
            options={"ordering": ["-scraped_at"],},
        ),
    ]
