# Generated by Django 4.2.11 on 2025-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="scrape_method",
            field=models.CharField(
                choices=[("api", "API"), ("selenium", "Selenium"), ("html", "HTML")],
                default="selenium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="price_selector",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="search_url_template",
            field=models.CharField(max_length=500),
        ),
    ]
